framework:
    esi: true
    trusted_hosts: ~
    fragments: ~
    assets: ~
    session:
        handler_id: ~
    serializer: { enabled: true }
    secret: "%env(APP_SECRET)%"
    validation:
        enable_annotations: true
    default_locale:  en_GB
    http_method_override: true
    php_errors:
        log: true
    cache:
        prefix_seed: shopware
        app: cache.adapter.filesystem
    templating:
        engines: ['twig']
    messenger:
        transports:
            default: enqueue://default
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default:
        routing:
            '*': default

sensio_framework_extra:
    router:
        annotations: false