security:
    firewalls:
        rest:
            pattern: ^/api/(v\d+/)?(?!(auth|info|entity-schema))
            stateless: true
            provider: rest
            anonymous: true
            guard:
                entry_point: Shopware\Rest\Firewall\TokenAuthenticator
                authenticators:
                    - Shopware\Rest\Firewall\TokenAuthenticator
                    - Shopware\Rest\Firewall\JWTAuthenticator

        storefront_api:
            pattern: ^/storefront-api/
            stateless: true
            provider: rest
            guard:
                authenticator:
                  - Shopware\StorefrontApi\Firewall\ApplicationAuthenticator

        storefront:
            pattern: ^/(?!(_profiler|_wdt|_error|admin|storefront-api|api))
            stateless: true
            provider: rest
            guard:
                authenticator:
                  - Shopware\StorefrontApi\Firewall\ApplicationAuthenticator

    access_control:
        - { path: ^/api/v\d+/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v\d+/info, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v\d+/entity-schema.json, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_ADMIN }
        - { path: ^/storefront-api, roles: ROLE_APPLICATION }

    providers:
        rest:
            id: Shopware\Rest\Firewall\RestUserProvider
