framework:
    esi: true
    csrf_protection: ~
    trusted_hosts: ~
    fragments: ~
    assets: ~
    session: ~
    serializer: { enabled: true }
    secret: "%env(APP_SECRET)%"
    validation:
        enable_annotations: true
    default_locale:  en_GB
    http_method_override: true
    php_errors:
        log: true
    cache:
        prefix_seed: shopware
        app: cache.adapter.filesystem

shopware:
    filesystem:
        private:
            type: "local"
            config:
                root: "%kernel.project_dir%/files"
        public:
            type: "local"
            config:
                root: "%kernel.project_dir%/public"

    cdn:
        url: ~
        strategy: "md5"

    api:
      max_limit: 500
      allowed_limits: [1, 5, 10, 25, 50, 75, 100, 500]