variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    IMAGE_TAG: shopware/development:latest

build:
    stage: build
    only:
        - master
    services:
        - name: docker:dind
          alias: docker
    before_script:
        - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
    script:
        - docker build -t $IMAGE_TAG dev-ops/docker/containers/app
        - docker push $IMAGE_TAG

