version: '3.3'

services:
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    environment:
      TENANT_ID: "43210f5d06f6411cba1794db3f834477"
    volumes:
      - .:/app
      - ~/.composer/cache:/.composer/cache
      - ~/.npm:/home/application/.npm

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
