version: '3.3'

services:
  app_server:
    build:
      context: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - .:/app
      - ~/.composer:/.composer
    tmpfs:
      - /tmp:mode=1777

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  app_cypress:
    image: cypress/browsers:node10.2.1-chrome74
    tty: true
    links:
      - app_server:docker.vm
    environment:
      - CYPRESS_baseUrl=http://docker.vm:8000
    depends_on:
      - app_server
    volumes:
      - .:/app
      - ./platform/src/Administration/Resources/e2e:/e2e-Administration
      - ./platform/src/Storefront/Resources/e2e:/e2e-Storefront

  adminer:
    image: adminer:latest
    links:
      - app_mysql:mysql
