administration:
    resource: ../vendor/shopware/platform/src/Administration/Controller/
    type: annotation

api:
    resource: ../vendor/shopware/platform/src/Core/Framework/Api/Controller/
    type: annotation

api-price-actions:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Cart/
    type: annotation

api-product-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/Product/
    type: annotation

api-media-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/Media/
    type: annotation

api-mail-template-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/MailTemplate/
    type: annotation

api-order-actions:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Order/
    type: annotation

api-snippet-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Snippet/
    type: annotation

api-attribute-set-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Attribute/
    type: annotation

api-user-recovery-actions:
    resource: ../vendor/shopware/platform/src/Core/System/User/Recovery
    type: annotation

api-system-config-actions:
    resource: ../vendor/shopware/platform/src/Core/System/SystemConfig
    type: annotation

storefront-product-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Product/Storefront/
    type: annotation

storefront-context-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Context/Storefront/
    type: annotation

storefront-checkout-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Cart/Storefront/
    type: annotation

storefront-customer-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Customer/Storefront/
    type: annotation

storefront-category-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Category/Storefront/
    type: annotation

storefront-sales-channel-api:
    resource: ../vendor/shopware/platform/src/Core/System/SalesChannel/Storefront/
    type: annotation

storefront-cms-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Cms/Storefront/
    type: annotation

payment:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Payment/
    type: annotation