administration:
    resource: ../vendor/shopware/platform/src/Administration/Controller/
    type: annotation

api:
    resource: ../vendor/shopware/platform/src/Core/Framework/Api/Controller/
    type: annotation

api-price-actions:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Cart/
    type: annotation

api-product-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/Product/
    type: annotation

api-media-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/Media/
    type: annotation

api-mail-template-actions:
    resource: ../vendor/shopware/platform/src/Core/Content/MailTemplate/
    type: annotation

api-order-actions:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Order/
    type: annotation

api-snippet-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Snippet/
    type: annotation

api-attribute-set-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Attribute/
    type: annotation

api-user-recovery-actions:
    resource: ../vendor/shopware/platform/src/Core/System/User/Recovery
    type: annotation

api-system-config-actions:
    resource: ../vendor/shopware/platform/src/Core/System/SystemConfig
    type: annotation

api-plugin-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Plugin/
    type: annotation

api-store-actions:
    resource: ../vendor/shopware/platform/src/Core/Framework/Store/
    type: annotation

number-range-api:
    resource: ../vendor/shopware/platform/src/Core/System/NumberRange/
    type: annotation

payment:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Payment/
    type: annotation

sales-channel-product-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Product/SalesChannel/
    type: annotation

sales-channel-checkout-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Cart/SalesChannel/
    type: annotation

sales-channel-customer-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Customer/SalesChannel/
    type: annotation

sales-channel-category-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Category/SalesChannel/
    type: annotation

sales-channel-api:
    resource: ../vendor/shopware/platform/src/Core/System/SalesChannel/SalesChannel/
    type: annotation

sales-channel-cms-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Cms/SalesChannel/
    type: annotation
