administration:
    resource: ../vendor/shopware/platform/src/Administration/Controller/
    type: annotation

api:
    resource: ../vendor/shopware/platform/src/Core/Framework/Api/Controller/
    type: annotation

storefront-product-api:
    resource: ../vendor/shopware/platform/src/Core/Content/Product/
    type: annotation

storefront-context-api:
    resource: ../vendor/shopware/platform/src/Core/Application/Context/
    type: annotation

storefront-checkout-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Cart/
    type: annotation

storefront-customer-api:
    resource: ../vendor/shopware/platform/src/Core/Checkout/Customer/
    type: annotation