storefront-framework:
    resource: ../vendor/shopware/platform/src/Storefront/Framework/Controller
    type: annotation

storefront:
    resource: ../vendor/shopware/platform/src/Storefront/Controller
    type: annotation

storefront-action:
    resource: ../vendor/shopware/platform/src/Storefront/ActionController
    type: annotation