storefront-framework:
    resource: ../vendor/shopware/platform/src/Storefront/Framework/Controller
    type: annotation

storefront-page:
    resource: ../vendor/shopware/platform/src/Storefront/PageController
    type: annotation

storefront-pagelet:
    resource: ../vendor/shopware/platform/src/Storefront/PageletController
    type: annotation
