#override defaults for dev
version: "3.3"

services:
  app_server:
    ports:
      - "8000:80"
      - "8080:8080"
    environment:
          TENANT_ID: "__TENANT_ID__"

  app_mysql:
    ports:
      - "4406:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/mysql-data
