services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    Shopware\Core\Checkout\Test\Payment\Handler\TestPaymentHandler:
        class: Shopware\Core\Checkout\Test\Payment\Handler\TestPaymentHandler
        tags: [payment.method]
        arguments: ['@order_transaction.repository']
    Shopware\Core\Framework\Test\Filesystem\Adapter\MemoryAdapterFactory:
        class: Shopware\Core\Framework\Test\Filesystem\Adapter\MemoryAdapterFactory
        tags: [Shopware\Core\Framework\Filesystem\FilesystemFactory]